Fix invalid column error message
ChameleonCloud/python-blazarclient pull request #17
Opened 2022-05-10 00:26 UTC by super-cooper

This bug occurred when a user passed only invalid column names to the client via a list-* command. Column names are intended to be processed by the `cliff` library, which compares the base columns which may be viewed by the user against any columns they may have included in their arguments. There is an unnecessary processing step in the `setup_columns` method which removes any invalid columns input by the user from the base list. That means that if only invalid columns are included, `cliff` receives an empty list of possible columns, which it treats as the only invalid configuration. Otherwise, it will simply ignore any invalid columns in the args provided by the user.

This patch fixes the pre-processing step in `setup_columns` by ensuring that the base columns visible via the command will always be passed to cliff. The reason why this step was not eliminated entirely was to retain the previous behavior of the Blazar client where a user may "look ahead" at columns added to the Blazar API which are not yet supported by their client by simply passing them to the command with `-c`.

2022-05-10 00:27 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [blazarclient - columns cannot be specified when listing allocations](https://trello.com/c/LFgABsoX/2652-blazarclient-columns-cannot-be-specified-when-listing-allocations)

2022-05-10 14:06 UTC, Mark-Powers requested changes
This seems to still not work as intended
```
# This looks correct
➜  python-blazarclient git:(column-bug) blazar host-allocation-list -c test
No recognized column names in ['test']. Recognized columns are ['reservations', 'resource_id'].
```
```
# But I think the same column name is being added twice
➜  python-blazarclient git:(column-bug) blazar host-allocation-list -c reservations
Field names must be unique!
```

2022-05-11 20:45 UTC, Mark-Powers requested changes
This has some strange behavior with `list_hosts` it seems. I think the best error message would include `self.list_columns` somewhere in it,

```
➜  python-blazarclient git:(column-bug) blazar host-list -c test               
No recognized column names in ['test']. Recognized columns are ['bios.release_date', 'type', 'supported_job_types.virtual', 'network_adapters.0.mounted', 'network_adapters.1.device', 'network_adapters.2.mac', 'placement.rack', 'storage_devices.0.model', 'network_adapters.1.enabled', 'network_adapters.0.mac', 'storage_devices.0.interface', 'uid', 'network_adapters.1.driver', 'network_adapters.3.driver', 'processor.cache_l3', 'chassis.serial', 'memory_mb', 'su_factor', 'network_adapters.0.rate', 'placement.node', 'network_adapters.3.interface', 'network_adapters.1.mounted', 'network_adapters.1.interface', 'hypervisor_hostname', 'architecture.platform_type', 'hypervisor_version', 'network_adapters.2.driver', 'network_adapters.1.rate', 'processor.model', 'network_adapters.2.bridged', 'network_adapters.3.device', 'processor.cache_l2', 'network_adapters.0.model', 'architecture.smp_size', 'network_adapters.3.vendor', 'network_adapters.2.model', 'network_adapters.2.management', 'cpu_arch', 'processor.cache_l1i', 'network_adapters.0.bridged', 'network_adapters.0.enabled', 'storage_devices.0.vendor', 'network_adapters.1.bridged', 'supported_job_types.deploy', 'network_adapters.1.management', 'network_adapters.0.interface', 'storage_devices.0.driver', 'local_gb', 'bios.vendor', 'gpu.gpu_count', 'network_adapters.2.enabled', 'monitoring.wattmeter', 'network_adapters.2.interface', 'network_adapters.2.rate', 'vcpus', 'network_adapters.1.mac', 'main_memory.humanized_ram_size', 'processor.vendor', 'updated_at', 'id', 'chassis.name', 'hypervisor_type', 'trust_id', 'storage_devices.0.device', 'network_adapters.0.device', 'network_adapters.3.enabled', 'gpu.gpu', 'main_memory.ram_size', 'network_adapters.2.vendor', 'node_name', 'network_adapters.0.driver', 'network_adapters.3.management', 'supported_job_types.besteffort', 'network_adapters.2.mounted', 'architecture.smt_size', 'gpu.gpu_model', 'network_adapters.3.mounted', 'service_name', 'network_adapters.1.vendor', 'storage_devices.0.rev', 'processor.version', 'network_adapters.3.mac', 'processor.instruction_set', 'network_adapters.0.management', 'storage_devices.0.humanized_size', 'chassis.manufacturer', 'network_adapters.3.rate', 'processor.cache_l1', 'processor.clock_speed', 'reservable', 'network_adapters.3.bridged', 'processor.cache_l1d', 'cpu_info', 'network_adapters.0.vendor', 'gpu.gpu_vendor', 'processor.other_description', 'network_adapters.3.model', 'network_adapters.2.device', 'storage_devices.0.size', 'status', 'node_type', 'created_at', 'network_adapters.1.model', 'bios.version', 'availability_zone'].

// no idea why this happens if using a column from above
➜  python-blazarclient git:(column-bug) blazar host-list -c su_factor
'gpu.gpu'
```
You'd have to check the other commands, but I think they also set `self.list_columns` as well.

2022-05-13 14:14 UTC, Mark-Powers approved these changes
Works great!

2022-05-16 15:41 UTC, merged